server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:stockdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.stockmanager: DEBUG

spring:
  profiles:
    active: dev 