server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:stockdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD:}

  sql:
    init:
      mode: always
      continue-on-error: true

  security:
    user:
      name: sa
      password: 

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
