server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:stockdb
    username: sa
    password:

  sql:
    init:
      mode: always
      continue-on-error: true

  security:
    user:
      name: sa
      password: 

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
