INSERT INTO product (name, category, quantity, expiration_date, created_at, updated_at) VALUES
('Tomates', 'LEGUMES', 20, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pommes', 'FRUITS', 15, DATEADD('DAY', 1, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lait', 'LAITIERS', 10, DATEADD('DAY', 3, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Poulet', 'VIANDES', 8, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carottes', 'LEGUMES', 30, DATEADD('DAY', 5, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fromage', 'LAITIERS', 5, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bananes', 'FRUITS', 25, DATEADD('DAY', 4, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Steak', 'VIANDES', 12, DATEADD('DAY', 1, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);