INSERT INTO product (name, category, quantity, expiration_date, created_at, updated_at)
VALUES
('Tomates', 'LEGUMES', 50, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pommes', 'FRUITS', 30, DATEADD('DAY', 5, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Poulet', 'VIANDES', 20, DATEADD('DAY', 1, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lait', 'LAITIERS', 40, DATEADD('DAY', 3, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carottes', 'LEGUMES', 60, DATEADD('DAY', 10, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bananes', 'FRUITS', 25, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Boeuf', 'VIANDES', 15, DATEADD('DAY', 4, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yaourt', 'LAITIERS', 35, DATEADD('DAY', 1, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Salade', 'LEGUMES', 45, DATEADD('DAY', 2, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fromage', 'LAITIERS', 22, DATEADD('DAY', 7, CURRENT_DATE), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 